routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});



Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::get('/employees/bin', 'EmployeeController@bin')->name('employees.bin');
Route::get('/employees/restore/{id}', 'EmployeeController@restore')->name('employees.restore');
Route::get('/employees/kill/{id}', 'EmployeeController@kill')->name('employees.kill');


Route::get('/employee/payroll/{id}', 'PayrollController@payrollIndex')->name('payrolls.show');
Route::get('/payrolls/create/{id}', 'PayrollController@create')->name('payrolls.create');
Route::post('/payrolls/{id}', 'PayrollController@store')->name('payrolls.store');
Route::get('/employee/payroll/{id}/edit', 'PayrollController@edit')->name('payrolls.edit');
Route::patch('/payrolls/update/{id}', 'PayrollController@update')->name('payrolls.update');

Route::delete('/payrolls/delete/{id}', 'PayrollController@destroy')->name('payrolls.destroy');
Route::get('/payroll/bin', 'PayrollController@bin')->name('payrolls.bin');
Route::get('/payroll/restore/{id}', 'PayrollController@restore')->name('payrolls.restore');
Route::get('/payroll/kill/{id}', 'PayrollController@kill')->name('payrolls.kill');

Route::get('/payrolls/download/{id}','DownloadController@pdfDownload')->name('payrolls.pdf');
Route::get('/payroll/single/{id}','DownloadController@singlePayroll')->name('singlepayroll.pdf');

Route::resources([
	'departments' => 'DepartmentController',
	'roles' => 'RoleController',
	'employees' => 'EmployeeController',
]);

app/Department.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Department extends Model
{
    protected $fillable=['name','slug'];
	
	public function roles(){
		return $this->hasMany('App\Role');
	}
}

app/Http/Controllers/DepartmentController.php
<?php

namespace App\Http\Controllers;

use App\Department;
use Session;
use Illuminate\Http\Request;

class DepartmentController extends Controller
{
     public function __construct()
    {
        $this->middleware('auth');
    }
	/**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('department.index', ['departments'=>Department::paginate(5)]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('department.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
			'name' => 'required'
		]);
		
		$department = new Department;
		$department->name = $request->name;
		$department->slug = str_slug($request->name);
		$department->save();
		
		Session::flash('success', 'department created');
		return redirect()->route('departments.index');
		
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($slug)
    {
        return view('department.show', ['department'=>Department::where('slug',$slug)->first()]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
         return view('department.edit', ['department'=>Department::findOrFail($id)]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
		$department = Department::findOrFail($id);
		
        $this->validate($request,[
			'name' => 'required'
		]);
		
		$department->name = $request->name;
		$department->slug = str_slug($request->name);
		$department->save();
		
		Session::flash('success', 'department updated');
		return redirect()->route('departments.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
         $department=Department::find($id);
		
		foreach($department->roles as $role){
			$role->delete();			
		}
		
		$department->delete();
		
		Session::flash('success', 'department deleted');
		return redirect()->route('departments.index');
    }
}

resources/views/department/create.blade.php
@extends('layouts.app')


@section('content')
	<div class="col-lg-12">
		<h1 class="page-header">New Department</h1>
	</div>
	

	<form action ="{{ route('departments.store') }}" method="POST">
		{{ csrf_field() }}
		
		<div class="form-group col-lg-6">
			<label for="name">Name</label>
			<input type="text" name="name" class="form-control">
		</div>
		
		<div class="form-group col-lg-12">			
			<button class ="btn.btn.success" type="submit">Save Department</button>			
		</div>
		
	</form>		   
@endsection

resources/views/department/edit.blade.php
@extends('layouts.app')

@section('content')
	
<div class="panel panel-default col-lg-8">
	<div class="panel-heading">
		<b> Edit Department:</b> {{ $department->name }}
   </div>
   
   <div class="panel-body">
		<form action ="{{ route('departments.update', ['id'=>$department->id]) }}" method="POST">
			{{ csrf_field() }}
			{{ method_field('PUT') }}
			
			<div class="form-group">
				<label for="name">Name</label>
				<input type="text" name="name" value="{{ $department->name }}" class="form-control">
			</div>
			
			<div class="form-group">
				<div class="text-center">
					<button class ="btn.btn.success" type="submit">Update Department</button>
				</div>
			</div>
			
		</form>	
	</div>
</div>

@endsection

resources/views/department/index.blade.php
@extends('layouts.app')


@section('content')
   <hr>	
	<h1 class="text-center">Departments</h1>	
	<hr>		
	<a href="{{ route('departments.create') }}" class="btn btn-primary">Create</a>
	<table class= "table table-hover">
		<thead>
			<th>Department name</th>			
			<th>Edit</th>			
			<th>Delete</th>							
		</thead>		
		<tbody>
			@if($departments->count() > 0)
				@foreach($departments as $department)
					<tr>
						<td>
							<a href="{{ route('departments.show', ['slug' => $department->slug ]) }}">{{ $department->name }}</a>
						</td>
						<td>
							<a href="{{ route('departments.edit', ['id' => $department->id ]) }}" class="btn btn-xs btn-info">Edit</a>							
						</td>
						<td>
							<form action="{{ route('departments.destroy', ['id' => $department->id ]) }}" method="POST">
								{{ csrf_field() }}
								{{ method_field('DELETE') }}
							
								<button class="btn btn-xs btn-danger">Delete</button>
							</form>
						</td>
					</tr>
				@endforeach
			@else
				<tr> 
					<th colspan="5" class="text-center">No Departments yet</th>
				</tr>
			@endif		
		</tbody>	
	</table>
		<div class="text-center">{{ $departments->links() }}</div>
@endsection

resources/views/department/show.blade.php
@extends('layouts.app')


@section('content')
    <div class="col-lg-12">
		<h1 class="page-header">Department: {{ $department->name }}</h1>
	</div>
		

	<table class= "table table-hover">
		<thead>
			<th>Role</th>
			<th>Salary</th>
		</thead>
		
		<tbody>
			@if($department->roles->count() > 0)
				@foreach($department->roles as $role)
					<tr>
						<td>
							<a href="{{ route('roles.show', ['slug'=>$role->slug])}}">{{ $role->name }}</a>
						</td>
						<td>{{ $role->salary }}</td>
					</tr>
				@endforeach
			@else
				<tr> 
					<th colspan="5" class="text-center">No Roles assigned in this department yet</th>
				</tr>
			@endif
		
		</tbody>
	
	</table>
		
@endsection